server.port: 9000

app:
  name: My app
  description: Welcome to ${app.name}

my:
  greeting: Hello World
  list:
    values: one,two,three

dbValues: "{connectionString: 'http://someurl', userName: 'foo', password: 'pass'}"

db:
  connection: "{connectionString: 'http://someurl', userName: 'foo', password: 'pass'}"
  host: 127.0.0.1
  port: 1200

#To expose actuator REST endpoints
management.endpoints.web.exposure.include: "*"

spring.cloud.config.uri: http://localhost:8888

spring.application.name: spring-boot-config
#spring.profiles.active: test